In [1]:
"""https://www.twse.com.tw/zh/trading/historical/mi-index.html"""
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
res = requests.get(
    "https://www.twse.com.tw/rwd/zh/afterTrading/MI_INDEX?response=html",
    headers={
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    }
)

In [3]:
print(res.text)

<!doctype html>
<html lang="zh">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> 報表 - TWSE 臺灣證券交易所 </title>
    <style>
    table { border-collapse: collapse; margin: 1em 0; }
    table, th, td { border: 1px solid lightgray; }
    table thead th, table thead td { text-align: center; background-color: #eee; }
    table thead div { font-size: 1.5em; padding: 10px; }
    table tbody tr:nth-child(even){ background-color:#f8f8f8; }
    td { padding: 4px; }
    td>p { margin: 0; text-align: center; }
    div.notes { margin: 2em 0 4em 0; line-height: 1.5em; }
    table tbody td { text-align: right; }
    table tbody td:first-child { text-align: left; }
    table tbody td:first-child + td { text-align: right; }
    </style>
</head>
<body>
<div>
















                <table>
                    <thead>
                    <tr>
                        <th colspan='4'>
                            <div>113年05月29日 大盤統計資訊</div>
                        </th>
                    </tr>
                    <tr>

                            <th>成交統計</th>

                            <th>成交金額(元)</th>

                            <th>成交股數(股)</th>

                            <th>成交筆數</th>

                    </tr>
                    </thead>
                    <tbody>

                        <tr align="center" style="font-size:14px;">

                                <td>1.一般股票</td>

                                <td>467,793,728,455</td>

                                <td>5,292,052,513</td>

                                <td>3,179,405</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>2.台灣存託憑證</td>

                                <td>132,369,994</td>

                                <td>32,822,710</td>

                                <td>5,510</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>3.受益憑證</td>

                                <td>0</td>

                                <td>0</td>

                                <td>0</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>4.ETF</td>

                                <td>20,407,412,780</td>

                                <td>1,114,213,237</td>

                                <td>314,075</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>5.受益證券</td>

                                <td>6,750,688</td>

                                <td>468,370</td>

                                <td>40</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>6.變更交易股票</td>

                                <td>15,560,418</td>

                                <td>2,237,519</td>

                                <td>971</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>7.認購(售)權證</td>

                                <td>4,159,110,290</td>

                                <td>3,624,000,000</td>

                                <td>137,572</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>8.轉換公司債</td>

                                <td>0</td>

                                <td>0</td>

                                <td>0</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>9.附認股權特別股</td>

                                <td>0</td>

                                <td>0</td>

                                <td>0</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>10.附認股權公司債</td>

                                <td>0</td>

                                <td>0</td>

                                <td>0</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>11.認股權憑證</td>

                                <td>0</td>

                                <td>0</td>

                                <td>0</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>12.公司債</td>

                                <td>0</td>

                                <td>0</td>

                                <td>0</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>13.ETN</td>

                                <td>54,626,130</td>

                                <td>6,675,000</td>

                                <td>232</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>14.創新板股票</td>

                                <td>198,153,910</td>

                                <td>2,597,043</td>

                                <td>1,487</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>15.創新板-變更交易方法股票</td>

                                <td>0</td>

                                <td>0</td>

                                <td>0</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>證券合計(1+6+14+15)</td>

                                <td>468,007,442,783</td>

                                <td>5,296,887,075</td>

                                <td>3,181,863</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>總計(1~15)</td>

                                <td>492,767,712,665</td>

                                <td>10,075,066,392</td>

                                <td>3,639,292</td>

                        </tr>

                    </tbody>
                </table>





                <table>
                    <thead>
                    <tr>
                        <th colspan='3'>
                            <div>漲跌證券數合計</div>
                        </th>
                    </tr>
                    <tr>

                            <th>類型</th>

                            <th>整體市場</th>

                            <th>股票</th>

                    </tr>
                    </thead>
                    <tbody>

                        <tr align="center" style="font-size:14px;">

                                <td>上漲(漲停)</td>

                                <td>6,233(33)</td>

                                <td>396(20)</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>下跌(跌停)</td>

                                <td>9,907(49)</td>

                                <td>545(0)</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>持平</td>

                                <td>994</td>

                                <td>67</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>未成交</td>

                                <td>19,047</td>

                                <td>2</td>

                        </tr>

                        <tr align="center" style="font-size:14px;">

                                <td>無比價</td>

                                <td>3,011</td>

                                <td>1</td>

                        </tr>

                    </tbody>
                </table>

                    <div class="notes">
                        <b>說明：</b>
                        <ol style="list-style-type: none">

                                <li>"漲跌價差"為當日收盤價與前一日收盤價比較。</li>

                                <li>"無比價"含前一日無收盤價、當日除權、除息、新上市、恢復交易者。</li>

                                <li>外幣成交值係以本公司當日下午3時30分公告匯率換算後加入成交金額。公告匯率請參考本公司首頁>產品與服務>交易系統>雙幣ETF專區>代號對應及每日公告匯率。</li>

                        </ol>
                    </div>










</div>
</body>
</html>

In [4]:
soup = BeautifulSoup(res.text, "html.parser")

In [5]:
table_tag_list = soup.select("table")
table_tag_list.__len__()

2

In [6]:
df_list = pd.read_html(str(table_tag_list[1]))
df = df_list[0]

/var/folders/_k/k5dry95j0q5d35_9pn5d86vm0000gn/T/ipykernel_35019/1590868598.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_list = pd.read_html(str(table_tag_list[1]))

In [7]:
df

  漲跌證券數合計
       類型       整體市場       股票
0  上漲(漲停)  6,233(33)  396(20)
1  下跌(跌停)  9,907(49)   545(0)
2      持平        994       67
3     未成交      19047        2
4     無比價       3011        1

In [8]:
df.columns

MultiIndex([('漲跌證券數合計',   '類型'),
            ('漲跌證券數合計', '整體市場'),
            ('漲跌證券數合計',   '股票')],
           )

In [9]:
df.loc[0:3:, :]

  漲跌證券數合計
       類型       整體市場       股票
0  上漲(漲停)  6,233(33)  396(20)
1  下跌(跌停)  9,907(49)   545(0)
2      持平        994       67
3     未成交      19047        2

In [10]:
df.loc[:, ('漲跌證券數合計',   '類型')]

0    上漲(漲停)
1    下跌(跌停)
2        持平
3       未成交
4       無比價
Name: (漲跌證券數合計, 類型), dtype: object

In [11]:
df.get("漲跌證券數合計")

       類型       整體市場       股票
0  上漲(漲停)  6,233(33)  396(20)
1  下跌(跌停)  9,907(49)   545(0)
2      持平        994       67
3     未成交      19047        2
4     無比價       3011        1

In [12]:
df["漲跌證券數合計"]

       類型       整體市場       股票
0  上漲(漲停)  6,233(33)  396(20)
1  下跌(跌停)  9,907(49)   545(0)
2      持平        994       67
3     未成交      19047        2
4     無比價       3011        1

In [13]:
df["漲跌證券數合計"]["類型"]

0    上漲(漲停)
1    下跌(跌停)
2        持平
3       未成交
4       無比價
Name: 類型, dtype: object